name: Prepare DPD database

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: joyzoursky/python-chromedriver:3.9
    timeout-minutes: 360  # Increased timeout to 6 hours

    steps:
      - uses: actions/checkout@v4

      - name: It may take hours to complete
        run: echo "It may take hours to complete, perhaps will ask dpd for full Goldendict build"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyglossary bs4 webdriver-manager selenium lxml

      - name: Download & extract dpd-goldendict.zip
        run: |
          wget -q -O dpd-goldendict.zip https://github.com/digitalpalidictionary/digitalpalidictionary/releases/latest/download/dpd-goldendict.zip
          unzip dpd-goldendict.zip -d tabfile

      - name: Convert to Tabfile
        run: |
          pyglossary tabfile/dpd/dpd.ifo tabfile/dpd/dpd.txt --read-format=Stardict --write-format=Tabfile
          pyglossary tabfile/dpd-deconstructor/dpd-deconstructor.ifo tabfile/dpd-deconstructor/dpd-deconstructor.txt --read-format=Stardict --write-format=Tabfile

      - name: List tabfile directory contents
        run: |
          ls -lh ${{ github.workspace }}/tabfile

      - name: Start Python HTTP Server
        run: |
          python -m http.server 8080 --directory ${{ github.workspace }}/tabfile &
          echo $! > server_pid.txt
          sleep 5  # Give the server a moment to start

      - name: Test Python HTTP Server
        run: |
          curl http://127.0.0.1:8080/dpd/res/main.js

      - name: Print System Info
        run: |
          lscpu
          free -h
          df -h

      - name: Generate DPD, declension, conjugation DB
        run: python main_dpd_to_sqlite.py

      - name: Generate DPD deconstructor DB
        run: python dpd_deconstructor_to_sqlite.py

      - name: Stop Python HTTP Server
        run: |
          kill $(cat server_pid.txt)
          rm server_pid.txt

      - name: Zip SQLite database
        run: |
          zip dpd-databases.zip ./*.db ./*.txt

      - name: Generate version tag
        id: version
        run: |
          echo "VERSION=v$(date +'%y.%-m.%-d')" >> "$GITHUB_ENV"
          echo "use tag name: v$(date +'%y.%-m.%-d')"

      - name: Create Github release
        uses: softprops/action-gh-release@v2
        with:
          name: auto build dpd ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          draft: true
          prerelease: false
          make_latest: true
          files: ./dpd-databases.zip

      - name: Notify API server
        run: |
          curl -X POST https://api.tipitakapali.org/api/auto-update-db \
          -H "Content-Type: application/json" \
          -d '{"token": "${{ secrets.UPDATE_KEY }}", "version": "${{ env.VERSION }}", "releaseUrl": "https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/dpd-databases.zip"}'